require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'gongshu066' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'gongshu066Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # Xcode 14.3+/15 compat: RN 0.66's yoga trips -Wbitwise-instead-of-logical,
    # which the pod builds with -Werror. Demote it for the Yoga target only.
    installer.pods_project.targets.each do |target|
      if target.name == "Yoga"
        # -Werror is baked into the podspec compiler_flags (xcconfig), so
        # build settings cannot demote it; strip it from the xcconfig files.
        target.build_configurations.each do |config|
          ref = config.base_configuration_reference
          next unless ref && ref.real_path && File.exist?(ref.real_path)
          text = File.read(ref.real_path)
          File.write(ref.real_path, text.gsub(/(\s)-Werror(\s)/, '\1\2'))
        end
      end
    end
  end
end